In [2]:
import pandas as pd
import numpy as np

In [23]:
df = pd.DataFrame({
    'age': [12, 13, 14, 16], 
    'weight': [41.1, 34.5, 83.2, 90.1], 
    'height': ['1.72', '1.74', '1.91', '1.54']
    })
df.info()
df = df.astype(float)
df.astype({'age': int})




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      int64  
 1   weight  4 non-null      float64
 2   height  4 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


age  weight  height
0   12    41.1    1.72
1   13    34.5    1.74
2   14    83.2    1.91
3   16    90.1    1.54

In [24]:
df.loc[2, 'weight'] = np.nan
df.loc[1, :] = np.nan
df


age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [26]:
df.dropna()
df.dropna(how='any', axis=0) # 하나라도 NA면 삭제
df.dropna(how='all', axis=0) # 모두다 NA 면 삭제 
df.dropna(thresh=1, axis=0) # 관측치 중 몇개가 NA가 아니냐?
df.dropna(how='any', axis=0)
df.dropna(thresh=df.shape[1], axis=0)
df
df.dropna(axis=1) # 축변환 
df.dropna(how='any', axis=1) # 하나라도 있음 삭제 
df.dropna(how='all', axis=1) # 모두다 NA 삭제 
df.dropna(axis=1, thresh=3)
print(df) # Inplace를 True라고 하지 않으면 실제 바뀌지 않는다
df.dropna(axis=1, thresh=3, inplace=True)
print(df) # Inplace를 True라고 할경우만 df 바뀐다. 

    age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54
    age  height
0  12.0    1.72
1   NaN     NaN
2  14.0    1.91
3  16.0    1.54


In [29]:
# 정렬 기법 배우기 
df = pd.DataFrame({
    'age': [12, 13, 14, 16], 
    'weight': [41.1, 41.1, 41.1, 90.1], 
    'height': ['1.72', '1.74', '1.91', '1.84']
    })
df.info()
df = df.astype(float)
df.astype({'age': int})

# 값의 크기에 따라서 정렬하기 
df.sort_values(by=['weight', 'height'], ascending=[False, True])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      int64  
 1   weight  4 non-null      float64
 2   height  4 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


age  weight  height
3  16.0    90.1    1.84
0  12.0    41.1    1.72
1  13.0    41.1    1.74
2  14.0    41.1    1.91

In [33]:
# 최대 최소 구하기 
df.max(axis=0)
df.min(axis=1)

0    1.72
1    1.74
2    1.91
3    1.84
dtype: float64

In [41]:
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.info(verbose=True, memory_usage='deep')
players.dtypes.value_counts()
players.market_value > 40 # Players 데이터 프레임에 Market Value가 40보다 크다 작다 판별 
players[players.market_value > 40] # 행에서 Filter하기 
players[players.market_value > 40].shape # 총 13명에대서 선택되고, 17개 열을 보존 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          465 non-null    object 
 1   club          465 non-null    object 
 2   age           465 non-null    int64  
 3   position      464 non-null    object 
 4   position_cat  465 non-null    int64  
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64  
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object 
 9   fpl_points    465 non-null    int64  
 10  region        465 non-null    int64  
 11  nationality   465 non-null    object 
 12  new_foreign   465 non-null    int64  
 13  age_cat       465 non-null    int64  
 14  club_id       465 non-null    int64  
 15  big_club      465 non-null    int64  
 16  new_signing   465 non-null    int64  
dtypes: float64(2), int64(10), object(5)
memory usage: 190.7 KB


(13, 17)

In [51]:
players.position.unique()
players.position.unique().size
players.position.isin(['LB', 'CB', 'RB']) # 축약형 명령어 
# 원래는 의미상 
#players.position=="LB" or players.position=="CB" or players.position=="RB" 
players.loc[players.position.isin(['LB', 'CB', 'RB'])]
# True False를 직접 사용해서 선택 

players.market_value.between(40,50)
players[players.market_value.between(40,50)]
players.age <= 25
players.loc[players.age <= 25]


name      club  age position  position_cat  market_value  \
5        Hector Bellerin   Arsenal   22       RB             3          30.0   
8       Shkodran Mustafi   Arsenal   25       CB             3          30.0   
9             Alex Iwobi   Arsenal   21       LW             1          10.0   
10          Granit Xhaka   Arsenal   24       DM             2          35.0   
11          Granit Xhaka   Arsenal   24       DM             2          35.0   
..                   ...       ...  ...      ...           ...           ...   
456         Pedro Obiang  West+Ham   25       CM             2           9.0   
460  Edimilson Fernandes  West+Ham   21       CM             2           5.0   
461       Arthur Masuaku  West+Ham   23       LB             3           7.0   
462            Sam Byram  West+Ham   23       RB             3           4.5   
463      Ashley Fletcher  West+Ham   21       CF             1           1.0   

     page_views  fpl_value fpl_sel  fpl_points  region  nationality  \
5          1675        6.0  13.70%         119       2        Spain   
8          1877        5.5   4.00%          90       2      Germany   
9          1812        5.5   1.00%          89       4      Nigeria   
10         1815        5.5   2.00%          85       2  Switzerland   
11         1815        5.5   2.00%          85       2  Switzerland   
..          ...        ...     ...         ...     ...          ...   
456         286        4.5   0.30%          55       2        Spain   
460         288        4.5   0.40%          38       2  Switzerland   
461         199        4.5   0.20%          34       4     Congo DR   
462         198        4.5   0.30%          29       1      England   
463         412        4.5   5.90%          16       1      England   

     new_foreign  age_cat  club_id  big_club  new_signing  
5              0        2        1         1            0  
8              0        3        1         1            1  
9              0        1        1         1            0  
10             0        2        1         1            0  
11             0        2        1         1            0  
..           ...      ...      ...       ...          ...  
456            0        3       20         0            0  
460            0        1       20         0            1  
461            0        2       20         0            1  
462            0        2       20         0            0  
463            0        1       20         0            1  

[172 rows x 17 columns]

In [53]:
#일반적으로 파이썬 조건문은 and/or Pandas dataframe Series간 조건문 결합에는  &/|을 쓴다. 
(players.position=="LB") | (players.position=="CB")

0      False
1      False
2      False
3      False
4       True
       ...  
460    False
461     True
462    False
463    False
464    False
Name: position, Length: 465, dtype: bool

In [54]:
players[
        (players.position == 'LB') & 
        (players.age <= 25)
        ]

players[
        (players.position == 'LB') & 
        (players.age <= 25) & 
        (players.market_value >= 10)
        ]
players[
        (players.position == 'LB') &
        (players.age <= 25) &
        (players.market_value >= 10) &
        ~(players.club.isin(['Tottenham', 'Arsenal']))
        ]


name               club  age position  position_cat  \
236  Alberto Moreno          Liverpool   25       LB             3   
281       Luke Shaw  Manchester+United   22       LB             3   

     market_value  page_views  fpl_value fpl_sel  fpl_points  region  \
236          10.0         397        4.5   0.30%           8       2   
281          20.0         947        5.0   0.40%          45       1   

    nationality  new_foreign  age_cat  club_id  big_club  new_signing  
236       Spain            0        3       10         1            0  
281     England            0        2       12         1            0

In [60]:
# 조건식 걸기-2D 
chelsea_23under = (players.club == 'Chelsea') & (players.age.le(23))
players.loc[chelsea_23under, ['position', 'market_value']]
p_cols = players.columns.str.startswith('p')
players.loc[chelsea_23under, p_cols]
players[chelsea_23under]['position']
players.loc[chelsea_23under, 'position']
players.loc[[0, 132], ('name', 'market_value')]


name  market_value
0    Alexis Sanchez          65.0
132  Connor Wickham           6.0

In [68]:
# 중복 관측치 제거  
players.duplicated()
players[players.duplicated()]
players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'])]
players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'])].shape
players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'], keep='last')]
players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'], keep=False)]
players.drop_duplicates(keep='first') # drop 하고, 처음것만 살린다. 


club position  position_cat  page_views  fpl_value fpl_sel  \
0     Arsenal       LW             1        4329       12.0  17.10%   
1     Arsenal       AM             1        4395        9.5   5.60%   
2     Arsenal       GK             4        1529        5.5   5.90%   
3     Arsenal       RW             1        2393        7.5   1.50%   
4     Arsenal       CB             3         912        6.0   0.70%   
..        ...      ...           ...         ...        ...     ...   
460  West+Ham       CM             2         288        4.5   0.40%   
461  West+Ham       LB             3         199        4.5   0.20%   
462  West+Ham       RB             3         198        4.5   0.30%   
463  West+Ham       CF             1         412        4.5   5.90%   
464  West+Ham       CF             1         214        5.5   0.10%   

     fpl_points  region     nationality  new_foreign  age_cat  club_id  \
0           264       3           Chile            0        4        1   
1           167       2         Germany            0        4        1   
2           134       2  Czech Republic            0        6        1   
3           122       1         England            0        4        1   
4           121       2          France            0        4        1   
..          ...     ...             ...          ...      ...      ...   
460          38       2     Switzerland            0        1       20   
461          34       4        Congo DR            0        2       20   
462          29       1         England            0        2       20   
463          16       1         England            0        1       20   
464          12       4         Senegal            0        3       20   

     big_club  new_signing  
0           1            0  
1           1            0  
2           1            0  
3           1            0  
4           1            0  
..        ...          ...  
460         0            1  
461         0            1  
462         0            0  
463         0            1  
464         0            0  

[465 rows x 14 columns]

In [69]:
#관측치 제거 
players.drop(labels=19, axis=0) #상하 동일
players.drop(index=19) # 상하동일 
players.drop(index=[19, 20, 21, 231, 10]) # 특정인덱스 지정 
players.drop(labels=['age', 'market_value'], axis='columns')
players.drop(columns=['age', 'market_value', 'name'])


club position  position_cat  page_views  fpl_value fpl_sel  \
0     Arsenal       LW             1        4329       12.0  17.10%   
1     Arsenal       AM             1        4395        9.5   5.60%   
2     Arsenal       GK             4        1529        5.5   5.90%   
3     Arsenal       RW             1        2393        7.5   1.50%   
4     Arsenal       CB             3         912        6.0   0.70%   
..        ...      ...           ...         ...        ...     ...   
460  West+Ham       CM             2         288        4.5   0.40%   
461  West+Ham       LB             3         199        4.5   0.20%   
462  West+Ham       RB             3         198        4.5   0.30%   
463  West+Ham       CF             1         412        4.5   5.90%   
464  West+Ham       CF             1         214        5.5   0.10%   

     fpl_points  region     nationality  new_foreign  age_cat  club_id  \
0           264       3           Chile            0        4        1   
1           167       2         Germany            0        4        1   
2           134       2  Czech Republic            0        6        1   
3           122       1         England            0        4        1   
4           121       2          France            0        4        1   
..          ...     ...             ...          ...      ...      ...   
460          38       2     Switzerland            0        1       20   
461          34       4        Congo DR            0        2       20   
462          29       1         England            0        2       20   
463          16       1         England            0        1       20   
464          12       4         Senegal            0        3       20   

     big_club  new_signing  
0           1            0  
1           1            0  
2           1            0  
3           1            0  
4           1            0  
..        ...          ...  
460         0            1  
461         0            1  
462         0            0  
463         0            1  
464         0            0  

[465 rows x 14 columns]

In [75]:
# Aggregate 함수  
players[["age","position_cat"]].agg('mean')
players.new_signing.mean()
players[["age","position_cat"]].agg(np.min)
players.select_dtypes(np.number).agg(np.min) # 숫자인 애들만 뽑아서 
players.select_dtypes(np.number).agg(['min', 'max', 'mean'])
players.loc[:, ['market_value', 'fpl_value']].transform(lambda x: x * 0.91) # 함수 적용하여 변환 
players.loc[:, ['market_value', 'fpl_value']] * 0.91



market_value  fpl_value
0          59.150     10.920
1          45.500      8.645
2           6.370      5.005
3          18.200      6.825
4          20.020      5.460
..            ...        ...
460         4.550      4.095
461         6.370      4.095
462         4.095      4.095
463         0.910      4.095
464         9.100      5.005

[465 rows x 2 columns]

In [79]:
# 칼럼에 대해서 특정함수 적용 입니다. 
def round_floats(x):
  if x.dtype == np.float64:
    return round(x)
  return x


players.apply(round_floats)
players.select_dtypes(np.float64).head()
players.select_dtypes(np.float64).apply(round_floats).head()


market_value  fpl_value
0          65.0       12.0
1          50.0       10.0
2           7.0        6.0
3          20.0        8.0
4          22.0        6.0

In [80]:
import numpy as np 
a=np.array([9, 5, 7, 6, 8])
print(a.size) #데이터 개수 
print(a.ndim) # 차원   
print(a.shape) # 차원별 크기 


5
1
(5,)


In [86]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3]) # 쉽다 
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]]) # 행마다 리스트로 지정해서 2차원 행렬을 만든다.

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)



((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [89]:
# Create an array of ones
ones = np.ones((10, 2))
ones
# You can change the datatype with .astype()
ones.astype(int)
zeros = np.zeros((5, 3, 3))
zeros
zeros.dtype
zeros





array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [91]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))
# Set random seed to 0
np.random.seed(0)
# Make 'random' numbers
np.random.randint(10, size=(5, 3))
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df



0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [95]:
import numpy as np 
a=np.array([9, 5, 7, 6, 8])
b=np.array([1, 1, 1, 1, 2])
f=a*b #(element-wise multiplications)
f # 일반적인 요소별 연산입니다. 
np.dot(a,b) # 벡터 내적, 행렬곱 하는 방식 a행벡터, b가 열벡터 

43

In [100]:
a.mean()
np.mean(a) # 남의 코드 보면 이런방식이 많이 쓰인다. 
a.min()
np.min(a) # numpy 연산이란걸 보다 명확히 하기 위해서 

5

In [103]:
np.linspace(-5,4,10)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [105]:
# Find the sum
np.sum(a1)
# Find the mean
np.mean(a2)
# Find the max
np.max(a2)
# Find the min
np.min(a2)
# Find the log of an array
np.log(a1)
# Find the exponential of an array
np.exp(a1)
# You can also use np.square()
np.square(a1)
print(a1)
np.exp(a1)

[1 2 3]


array([ 2.71828183,  7.3890561 , 20.08553692])

In [108]:
# Demo of variance
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])
np.var(high_var_array), np.var(low_var_array)
np.std(high_var_array), np.std(low_var_array)
# The standard deviation is the square root of the variance
np.sqrt(np.var(high_var_array))



2072.711623024829

In [121]:
# Comparison
a1>a2 # 차원이 다름에도 비교 가능 
a1>a2[0,:] #추천은 이것 
a1>a2
a1[0]=100
a1>a2
a1>=a2
a1>5
a1==a1 
a1 == a2 # 차원이 달라도 size끼리 서로의 배수이면 

# Argument 
# Return the indices that would sort an array
np.argsort(a1)
# No axis
np.argmin(a1)
# Across the horizontal
np.argmin(a2, axis=0)


array([0, 0, 0])

In [133]:
a1+a2 # Size가 배수면 자동으로 복사 조심 

array([[101. ,   4. ,   6.3],
       [104. ,   7. ,   9.5]])

In [132]:
# Reshaping Data 
a2
a2.reshape(2, 3, 1)
a2.T
a2.T.shape
matrix = np.random.random(size=(5,3,3))
matrix
matrix.shape
matrix.T
matrix.T.shape



(3, 3, 5)